2 - Write a Script to Read the CSV File and Display the Data

In [1]:
import csv
# Open the CSV file
with open('sales_data.csv', mode='r') as file:
    csv_reader = csv.reader(file)
    # Display the data
    for row in csv_reader:
        print(row)

['Date', 'Product', 'Sales', 'Customer_Age', 'Customer_Location', 'Payment_Method']
['20230101', 'Laptop', '1200.00', '34', 'New York', 'Credit Card']
['20230102', 'Smartphone', '800.00', '22', 'California', 'Paypal']
['20230103', 'Tablet', '300.00', '45', 'Texas', 'Credit Card']
['20230104', 'Laptop', '1500.00', '31', 'Florida', 'Cash']
['20230105', 'Smartphone', '750.00', '27', 'New York', 'Paypal']
['20230106', 'Tablet', '250.00', '36', 'California', 'Credit Card']
['20230107', 'Laptop', '1100.00', '29', 'Texas', 'Cash']
['20230108', 'Smartphone', '900.00', '41', 'Florida', 'Credit Card']
['20230109', 'Tablet', '350.00', '28', 'New York', 'Paypal']
['20230110', 'Laptop', '1300.00', '33', 'California', 'Cash']

Extract Specific Information from the CSV File

    Extract the Total Sales
    Extract the average Customer Age

In [2]:
import csv
total_sales = 0
total_age = 0
customer_count = 0
with open('sales_data.csv', mode='r') as file:
    csv_reader = csv.reader(file)
    next(csv_reader)  # Skip the header row
    for row in csv_reader:
        sales = float(row[2])
        age = int(row[3])
        total_sales += sales
        total_age += age
        customer_count += 1
average_age = total_age / customer_count
print(f"Total Sales: ${total_sales}")
print(f"Average Customer Age: {average_age}")

Total Sales: $8450.0
Average Customer Age: 32.6

4 - Perform Data Cleaning Tasks

    Handle missing values and correct formatting issues

In [3]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('sales_data.csv')
# Fill missing values
df.fillna({'Sales': 0, 'Customer_Age': df['Customer_Age'].mean()}, inplace=True)
# Correct formatting issues (example: standardize customer location names)
df['Customer_Location'] = df['Customer_Location'].str.title()
print(df)

       Date     Product   Sales  Customer_Age Customer_Location Payment_Method
0  20230101      Laptop  1200.0            34          New York    Credit Card
1  20230102  Smartphone   800.0            22        California         Paypal
2  20230103      Tablet   300.0            45             Texas    Credit Card
3  20230104      Laptop  1500.0            31           Florida           Cash
4  20230105  Smartphone   750.0            27          New York         Paypal
5  20230106      Tablet   250.0            36        California    Credit Card
6  20230107      Laptop  1100.0            29             Texas           Cash
7  20230108  Smartphone   900.0            41           Florida    Credit Card
8  20230109      Tablet   350.0            28          New York         Paypal
9  20230110      Laptop  1300.0            33        California           Cash

5 - Use Pandas for Advanced Data Analysis

    Perform more advanced analysis using pandas, such as grouping and aggregating data5

In [4]:
import pandas as pd
# Load the CSV file
df = pd.read_csv('sales_data.csv')

# Group by product and calculate total sales
product_sales = df.groupby('Product')['Sales'].sum()
print("Total Sales by Product:")
print(product_sales)
# Calculate average sales by customer location
location_sales = df.groupby('Customer_Location')['Sales'].mean()
print("Average Sales by Customer Location:")
print(location_sales)
# Filter data for sales above a certain amount
high_sales = df[df['Sales'] > 1000]
print("Sales Above $1000:")
print(high_sales)

Total Sales by Product:
Product
Laptop        5100.0
Smartphone    2450.0
Tablet         900.0
Name: Sales, dtype: float64
Average Sales by Customer Location:
Customer_Location
California     783.333333
Florida       1200.000000
New York       766.666667
Texas          700.000000
Name: Sales, dtype: float64
Sales Above $1000:
       Date Product   Sales  Customer_Age Customer_Location Payment_Method
0  20230101  Laptop  1200.0            34          New York    Credit Card
3  20230104  Laptop  1500.0            31           Florida           Cash
6  20230107  Laptop  1100.0            29             Texas           Cash
9  20230110  Laptop  1300.0            33        California           Cash