In [ ]:
import pandas as pd
import numpy as np

In [ ]:
##### Part1: Create a 4x4 dimensional array-like object containing a mix of integer and object datatypes data.
### Part I: 1 - Print the array:
a = np.array([[1,2,3, 4],[20,15,46, 73],['toto', 'tata', 'mimi', 'momo'], ['green','red', 'yellow', 'black']])
print(a)

[['1' '2' '3' '4']
 ['20' '15' '46' '73']
 ['toto' 'tata' 'mimi' 'momo']
 ['green' 'red' 'yellow' 'black']]

In [ ]:
### Part I: 2 - Display the statistical summary.
a=pd.DataFrame(a)

print(a.describe())

        0  1  2  3
count   4  4  4  4
unique  4  4  4  4
top     1  2  3  4
freq    1  1  1  1

In [ ]:
##Part I: 3 - Display the shape of the array.
print(a.shape)

(4, 4)

In [ ]:
### Part I: 4 - Display the datatype.
print(a.dtypes)

0    object
1    object
2    object
3    object
dtype: object

In [ ]:
### Part I: 5 - Print the info() function of the array.
print(a.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4 non-null      object
 1   1       4 non-null      object
 2   2       4 non-null      object
 3   3       4 non-null      object
dtypes: object(4)
memory usage: 260.0+ bytes
None